# neocomplete の上位互換
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    set completeopt-=preview
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#max_list = 10000
    let g:deoplete#auto_complete_start_length = 1
'''


# denite 
[[plugins]]
repo = 'Shougo/denite.nvim'


# activate git on vim
[[plugins]]
repo = 'tpope/vim-fugitive'


# ctags tools
[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
on_ft = ['python']
hook_add = 'set tags+=~/.config/nvim/tags/pylibs.tags'
#    set statusline+=%{gutentags#statusline()}



# AUTO BRACKETS http://qiita.com/pepo/items/60c3ddb8925e49808a76
[[plugins]]
repo = 'cohama/lexima.vim'


# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'


# Resize window
[[plugins]]
repo = 'simeji/winresizer'


# quick-run 
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''let g:quickrun_config = {
      \   "_" :{
      \         "split" : "vertical",
      \         "runner" : "vimproc",
      \         "runner/vimproc/updatetime" : 40
      \         },
      \   "tex" : {
      \       'command' : 'latexmk',
      \       "outputter/buffer/split" : ":botright 8sp",
      \       'outputter/error/error' : 'quickfix',
      \       'hook/cd/directory': '%S:h',
      \       'exec': '%c %s'
      \   },
      \}'''
hook_add = 'set splitright'

 
## for LaTeX
#[[plugins]]
#repo = 'lervag/vimtex'
#hook_add = 'let g:vimtex_fold_envs = 0'
## hook_add = "let g:vimtex_view_general_viewer = 'mupdf'"
#hook_add = 'let g:vimtex_view_general_viewer = "/Applications/Skim.app/Contents/SharedSupport/displayline"
#hook_add = 'let g:vimtex_view_general_options = "-r @line @pdf @tex"'
#hook_add = 'let g:vimtex_view_general_options_latexmk = "-r 1"'


# vimproc is used for quickrun at least
[[plugins]]
repo = 'Shougo/vimproc'



#==========================
#
#      COLOR SCHEMES
#
#==========================
# color scheme
[[plugins]]
#repo = 'raphamorim/lucario'
#repo = 'fneu/breezy'
#repo = 'joshdick/onedark.vim'
#repo = 'altercation/vim-colors-solarized'
#repo = 'nanotech/jellybeans.vim'
#repo = 'drewtempelmeyer/palenight.vim'
#repo = 'jacoborus/tender.vim'
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''


# for airline color scheme
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
let g:airline_powerline_fonts = 1
'''


# for airline color scheme
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
#hook_add = 'let g:airline_solarized_bg="dark"'


# set airline as deviconed (I avoid using this plugin because of mozibake)
#[[plugins]]
#repo = 'ryanoasis/vim-devicons'
