# for markdown 
[[plugins]]
on_ft = ['markdown']
repo = 'plasticboy/vim-markdown'
hook_add = '''
    set nofoldenable
    let g:vim_markdown_folding_disabled = 1
    au BufRead,BufNewFile *.md set filetype=markdown
''' 


[[plugins]]
on_ft = ['markdown']
repo = 'previm/previm'
hook_add = '''
    let g:previm_open_cmd = "open -a 'Google Chrome'"
    au BufRead,BufNewFile *.md set filetype=markdown
'''
