# for markdown 
[[plugins]]
on_ft = ['markdown']
repo = 'plasticboy/vim-markdown'
hook_add = '''
    set nofoldenable
    let g:vim_markdown_folding_disabled = 1
    au BufRead,BufNewFile *.md set filetype=markdown
''' 


[[plugins]]
on_ft = ['markdown']
repo = 'previm/previm'
hook_add = '''
    let g:previm_open_cmd = "open -a 'Google Chrome'"
    au BufRead,BufNewFile *.md set filetype=markdown
'''


# linter
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'c', 'cpp', 'rust']
hook_add = '''
let g:ale_lint_on_text_changed = "normal"
let g:ale_lint_on_enter = 0
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
" linter
let g:ale_linters = {
    \ 'python': ['flake8'],
    \ 'c' : ['clang'],
    \ 'cpp' : ['clang'],
    \ 'rust' : ['rls'],
    \ }
" fixer
let g:ale_fixers = {
      \ 'python': ['autopep8', 'isort'],
      \ 'rust': ['rustfmt'],
      \ }
let g:ale_python_autopep8_options = '--aggressive'
let g:ale_rust_rls_toolchain = 'nightly'
let g:ale_completion_enabled = 0
let g:ale_fix_on_save = 0
let g:ale_sign_column_always = 1
" Set this. Airline will handle the rest.
let g:airline#extensions#ale#enabled = 1
'''
